### PR TITLE
Refactored Discord Webhooks. New LED support and others

### PR DESCRIPTION
**Pull request by zack-kyria**
+ Added support for H96 Max LEDS (also made is so LED is red when service is running and BLUE when service is down)
+ Refactored a bit the Discord Webhooks
+ following [@notheowner 's changes](https://github.com/Astu04/eMagisk/pull/6)  fixed `get_config` function initialization

### CODE REVIEW

**Comment by notheowner** [comment]
While personally I don't care for LED functionality.

* LED switching works on H96 Max
* Webhook works
* Timezone setting works

LGTM

**Review by Astu04 — CHANGES_REQUESTED** [review]
```
# This is for the X96 Mini and X96W Atvs. Can be adapted to other ATVs that have a led status indicator
led_red(){
	if [ -e /sys/class/leds/led-sys ]; then
		echo 0 > /sys/class/leds/led-sys/brightness
	elif [ -e /sys/class/leds/sys_led ]; then
		echo 0 > /sys/class/leds/sys_led/brightness
	elif [ -e /sys/class/leds/power-red ]; then
	    echo 1 > /sys/class/leds/power-red/brightness # H96MAX LED Management 
	fi
}

led_blue(){
	if [ -e /sys/class/leds/led-sys ]; then
		echo 1 > /sys/class/leds/led-sys/brightness
	elif [ -e /sys/class/leds/sys_led ]; then
		echo 1 > /sys/class/leds/sys_led/brightness
	elif [ -e /sys/class/leds/power-red ]; then
	    echo 0 > /sys/class/leds/power-red/brightness # H96MAX LED Management
	fi
}
```
Can you modify it this way? It should just work TM for that ATV too.

**Comment by zack-kyria** [comment]
Done. Yeah It was just leds so i didn't really pay attention.

**Comment by Astu04** [comment]
notheowner says it's good so I hope it works fine :) 
Thank you for your contribution!

**Pull request merged**
